from __future__ import annotations

import hashlib
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import cast

import pytest
from pytest import MonkeyPatch

import hecavex_radar.event_feeds as event_feeds
from hecavex_radar.event_feeds import (
    build_brand_event_feeds,
    build_event_feeds,
    build_event_feeds_from_files,
    write_event_feeds,
)
from hecavex_radar.review import _build_admission_source
from hecavex_radar.safety import stable_id

NOW = "2026-08-25T12:00:00.000Z"


def _history_event(
    domain: str,
    observed_at: str,
    *,
    event_type: str,
    previous_status: str | None = None,
    status: str = "suspected",
    reasons: list[str] | None = None,
    brand: str = "Example & <Bank>",
) -> dict[str, object]:
    signal_identifier = stable_id(domain.lower())
    payload: dict[str, object] = {
        "schemaVersion": 1,
        "signalId": signal_identifier,
        "eventType": event_type,
        "observedAt": observed_at,
        "domain": domain,
        "brand": brand,
        "sources": ["URLScan"],
        "status": status,
        "previousStatus": previous_status,
        "confidence": 91,
        "reasonCodes": reasons
        or (["first-publication"] if event_type == "status-transition" else ["brand-domain-match"]),
    }
    identity = {
        key: payload[key]
        for key in (
            "schemaVersion",
            "signalId",
            "eventType",
            "observedAt",
            "sources",
            "status",
            "previousStatus",
        )
    }
    canonical = json.dumps(identity, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    payload["eventId"] = hashlib.sha256(canonical.encode()).hexdigest()[:32]
    return payload


def _snapshot(*signals: tuple[str, str, str]) -> dict[str, object]:
    return {
        "schemaVersion": 2,
        "dataset": "live",
        "generatedAt": NOW,
        "lastSuccessfulSyncAt": NOW,
        "signals": [
            {
                "id": stable_id(domain.lower()),
                "domain": domain,
                "brand": brand,
                "firstSeen": first_seen,
            }
            for domain, brand, first_seen in signals
        ],
    }


def test_builds_distinct_events_without_publishing_a_raw_url() -> None:
    domain = "login-example[.]test"
    signal_identifier = stable_id(domain.lower())
    events = [
        _history_event(domain, "2026-08-25T09:00:00.000Z", event_type="observation"),
        _history_event(domain, "2026-08-25T10:00:00.000Z", event_type="observation"),
        _history_event(domain, "2026-08-25T10:00:00.000Z", event_type="status-transition"),
        _history_event(domain, "2026-08-25T11:00:00.000Z", event_type="observation"),
        _history_event(
            domain,
            "2026-08-25T11:30:00.000Z",
            event_type="status-transition",
            previous_status="suspected",
            status="offline",
            reasons=["source-status-change"],
        ),
    ]
    review = {
        "schemaVersion": 3,
        "dataset": "radar-review-decisions",
        "assessments": [
            {
                "id": "a" * 24,
                "signalId": signal_identifier,
                "domain": domain,
                "brand": "Example & <Bank>",
                "reviewedAt": "2026-08-25T11:30:00.000Z",
                "modifiedAt": "2026-08-25T11:45:00.000Z",
                "revoked": True,
                "admissionSource": _build_admission_source(
                    signal_id=signal_identifier,
                    domain=domain,
                    brand="Example & <Bank>",
                    observed_at="2026-08-25T09:00:00.000Z",
                    sources=["CertStream"],
                ),
            }
        ],
    }

    bundle = build_event_feeds(
        events,
        _snapshot((domain, "Example & <Bank>", "2026-08-25T09:00:00.000Z")),
        NOW,
        review,
    )

    assert [event["type"] for event in bundle.artifact["events"]] == [
        "retraction",
        "status-change",
        "reobservation",
        "first-publication",
    ]
    assert all(
        event["signalPath"] == f"/signals/{signal_identifier}/"
        for event in bundle.artifact["events"]
    )
    assert b"login-example.test" not in (
        bundle.event_json + bundle.atom + bundle.rss + bundle.json_feed
    )
    assert b"login-example[.]test" in bundle.event_json


def test_xml_is_escaped_and_every_item_link_is_a_stable_signal_path() -> None:
    domain = "escape-check[.]example"
    events = [
        _history_event(domain, "2026-08-25T10:00:00.000Z", event_type="status-transition")
    ]
    bundle = build_event_feeds(
        events,
        _snapshot((domain, "Example & <Bank>", "2026-08-25T10:00:00.000Z")),
        NOW,
    )

    assert b"Example &amp; &lt;Bank&gt;" in bundle.atom
    atom = ET.fromstring(bundle.atom)  # noqa: S314 - parses bytes generated by the test subject
    namespace = {"atom": "http://www.w3.org/2005/Atom"}
    atom_links = [link.attrib["href"] for link in atom.findall("atom:entry/atom:link", namespace)]
    rss = ET.fromstring(bundle.rss)  # noqa: S314 - parses bytes generated by the test subject
    rss_links = [cast(str, item.findtext("link")) for item in rss.findall("channel/item")]
    for link in atom_links + rss_links:
        assert re.fullmatch(r"https://radar\.hecavex\.com/signals/[a-f\d]{20}/", link)


def test_output_is_deterministic_and_latest_events_are_retained_when_truncated(
    monkeypatch: MonkeyPatch,
) -> None:
    monkeypatch.setattr(event_feeds, "MAXIMUM_FEED_EVENTS", 2)
    domains = [f"signal-{number}[.]example" for number in range(3)]
    events = [
        _history_event(
            domain,
            f"2026-08-25T0{number + 1}:00:00.000Z",
            event_type="status-transition",
            brand="Example",
        )
        for number, domain in enumerate(domains)
    ]
    snapshot = _snapshot(
        *((domain, "Example", f"2026-08-25T0{number + 1}:00:00.000Z") for number, domain in enumerate(domains))
    )

    first = build_event_feeds(events, snapshot, NOW)
    second = build_event_feeds(reversed(events), snapshot, NOW)

    assert first == second
    assert first.artifact["totalAvailable"] == 3
    assert first.artifact["truncated"] is True
    assert [event["domain"] for event in first.artifact["events"]] == list(reversed(domains[1:]))


def test_loader_and_atomic_writer_use_the_bounded_daily_archive(tmp_path: Path) -> None:
    domain = "from-file[.]example"
    event = _history_event(
        domain,
        "2026-08-25T10:00:00.000Z",
        event_type="status-transition",
        brand="Example",
    )
    archive = tmp_path / "history" / "daily" / "2026-08-25"
    archive.mkdir(parents=True)
    (archive / "events.ndjson").write_text(json.dumps(event) + "\n", encoding="utf-8")
    snapshot_path = tmp_path / "radar.json"
    snapshot_path.write_text(
        json.dumps(_snapshot((domain, "Example", "2026-08-25T10:00:00.000Z"))),
        encoding="utf-8",
    )

    bundle = build_event_feeds_from_files(tmp_path / "history", snapshot_path)
    paths = write_event_feeds(tmp_path / "public", bundle)

    assert set(paths) == {"events", "atom", "rss", "jsonFeed"}
    assert all(path.is_file() for path in paths.values())
    assert json.loads(paths["events"].read_text(encoding="utf-8"))["events"][0]["domain"] == domain
    ET.parse(paths["atom"])  # noqa: S314 - parses bytes generated by the test subject
    ET.parse(paths["rss"])  # noqa: S314 - parses bytes generated by the test subject


def test_rejects_refanged_or_inconsistent_history() -> None:
    domain = "raw.example"
    event = _history_event(domain, "2026-08-25T10:00:00.000Z", event_type="status-transition")
    with pytest.raises(ValueError, match="invalid event"):
        build_event_feeds(
            [event],
            _snapshot(("raw[.]example", "Example & <Bank>", "2026-08-25T10:00:00.000Z")),
            NOW,
        )


def test_excludes_events_outside_the_rolling_thirty_day_window() -> None:
    recent = "recent[.]example"
    old = "old[.]example"
    events = [
        _history_event(recent, "2026-08-25T10:00:00.000Z", event_type="status-transition"),
        _history_event(old, "2026-07-20T10:00:00.000Z", event_type="status-transition"),
    ]
    bundle = build_event_feeds(
        events,
        _snapshot(
            (recent, "Example & <Bank>", "2026-08-25T10:00:00.000Z"),
            (old, "Example & <Bank>", "2026-07-20T10:00:00.000Z"),
        ),
        NOW,
    )
    assert [event["domain"] for event in bundle.artifact["events"]] == [recent]


def test_per_brand_feeds_include_stable_unicode_slugs_and_honest_empty_views() -> None:
    domain = "brand-feed[.]example"
    global_bundle = build_event_feeds(
        [
            _history_event(
                domain,
                "2026-08-25T10:00:00.000Z",
                event_type="status-transition",
                brand="Šiaulių bankas",
            )
        ],
        _snapshot((domain, "Šiaulių bankas", "2026-08-25T10:00:00.000Z")),
        NOW,
    )

    feeds = build_brand_event_feeds(global_bundle.artifact, ["Šiaulių bankas", "Vinted"])
    by_brand = {feed.brand: feed for feed in feeds}
    assert by_brand["Šiaulių bankas"].slug == "siauliu-bankas"
    assert by_brand["Šiaulių bankas"].event_count == 1
    assert by_brand["Vinted"].event_count == 0
    vinted_json = json.loads(by_brand["Vinted"].json_feed)
    assert vinted_json["items"] == []
    assert vinted_json["feed_url"] == "https://radar.hecavex.com/data/brands/vinted/events.feed.json"
